// Converts Natural Earth countries GeoJSON into normalised continent polygons
// for the EruMind map game. Emits Dart source.
const fs = require('fs');

const gj = JSON.parse(fs.readFileSync('countries.geojson', 'utf8'));

// Projection bounds (equirectangular / plate carrée). Crop poles a bit.
const MIN_LNG = -180, MAX_LNG = 180;
const MAX_LAT = 84,  MIN_LAT = -78;
const ASPECT = (MAX_LNG - MIN_LNG) / (MAX_LAT - MIN_LAT); // ~2.22

const SIMPLIFY_TOL = 0.0018; // in normalised 0..1 units
const MIN_AREA = 0.00006;    // drop islands smaller than this (normalised)

// Natural Earth CONTINENT -> our continent id
const CONT_MAP = {
  'North America': 'north_america',
  'South America': 'south_america',
  'Europe': 'europe',
  'Africa': 'africa',
  'Asia': 'asia',
  'Oceania': 'australia',
  'Antarctica': 'antarctica',
};
// Per-country overrides (visual grouping for the game)
const ADMIN_OVERRIDE = {
  'Russia': 'asia',
};

function project([lng, lat]) {
  const x = (lng - MIN_LNG) / (MAX_LNG - MIN_LNG);
  const y = (MAX_LAT - lat) / (MAX_LAT - MIN_LAT);
  return [x, y];
}

// perpendicular distance point->segment
function perpDist(p, a, b) {
  const [px, py] = p, [ax, ay] = a, [bx, by] = b;
  const dx = bx - ax, dy = by - ay;
  const len2 = dx * dx + dy * dy;
  if (len2 === 0) return Math.hypot(px - ax, py - ay);
  let t = ((px - ax) * dx + (py - ay) * dy) / len2;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}

function douglasPeucker(pts, tol) {
  if (pts.length < 3) return pts;
  let maxD = 0, idx = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const d = perpDist(pts[i], pts[0], pts[pts.length - 1]);
    if (d > maxD) { maxD = d; idx = i; }
  }
  if (maxD > tol) {
    const left = douglasPeucker(pts.slice(0, idx + 1), tol);
    const right = douglasPeucker(pts.slice(idx), tol);
    return left.slice(0, -1).concat(right);
  }
  return [pts[0], pts[pts.length - 1]];
}

function polyArea(pts) {
  let a = 0;
  for (let i = 0; i < pts.length; i++) {
    const [x1, y1] = pts[i];
    const [x2, y2] = pts[(i + 1) % pts.length];
    a += x1 * y2 - x2 * y1;
  }
  return Math.abs(a) / 2;
}

const shapes = []; // { continentId, points: [[x,y],...] }

for (const f of gj.features) {
  const admin = f.properties.ADMIN;
  let contId = ADMIN_OVERRIDE[admin] || CONT_MAP[f.properties.CONTINENT];
  if (!contId) continue; // skip open ocean

  const geom = f.geometry;
  const rings = [];
  if (geom.type === 'Polygon') {
    rings.push(geom.coordinates[0]);
  } else if (geom.type === 'MultiPolygon') {
    for (const poly of geom.coordinates) rings.push(poly[0]);
  }

  for (const ring of rings) {
    let pts = ring.map(project);
    pts = douglasPeucker(pts, SIMPLIFY_TOL);
    if (pts.length < 3) continue;
    if (polyArea(pts) < MIN_AREA) continue;
    // clamp to 0..1 (Antarctica / far edges)
    pts = pts.map(([x, y]) => [
      Math.max(0, Math.min(1, x)),
      Math.max(0, Math.min(1, y)),
    ]);
    shapes.push({ continentId: contId, points: pts });
  }
}

// stats
const byCont = {};
let totalPts = 0;
for (const s of shapes) {
  byCont[s.continentId] = (byCont[s.continentId] || 0) + 1;
  totalPts += s.points.length;
}
console.error('polygons per continent:', byCont);
console.error('total polygons:', shapes.length, 'total points:', totalPts);

// emit Dart
let out = '';
out += "// GENERATED by tool/gen_shapes.js from Natural Earth ne_110m data.\n";
out += "// Do not edit by hand. Regenerate to change continent shapes.\n";
out += "import 'package:flutter/painting.dart';\n\n";
out += "/// Width / height ratio of the projected world map.\n";
out += `const double kMapAspect = ${ASPECT.toFixed(4)};\n\n`;
out += "/// One drawable landmass polygon, tagged with its continent id.\n";
out += "class ContinentShape {\n";
out += "  final String continentId;\n";
out += "  final List<Offset> points;\n";
out += "  const ContinentShape(this.continentId, this.points);\n";
out += "}\n\n";
out += "const List<ContinentShape> kWorldShapes = [\n";
for (const s of shapes) {
  out += `  ContinentShape('${s.continentId}', [\n`;
  let line = '    ';
  for (const [x, y] of s.points) {
    const tok = `Offset(${x.toFixed(4)}, ${y.toFixed(4)}), `;
    if (line.length + tok.length > 96) { out += line + '\n'; line = '    '; }
    line += tok;
  }
  out += line + '\n  ]),\n';
}
out += "];\n";

fs.writeFileSync('world_shapes.dart', out);
console.error('wrote world_shapes.dart (' + out.length + ' bytes)');
